package mindgarden.model;

import java.time.LocalDateTime;

/**
 * Represents a single journal entry written by the user.
 */
public class JournalEntry {

    private int id; // Database primary key
    private String content; // The text content of the journal entry
    private LocalDateTime timestamp;
    private boolean isDraft;
    private String title;
    private String mood;

    // Constructor for creating new entries (ID is auto-generated by DB)
    public JournalEntry(String content) {
        this.content = content;
        this.timestamp = LocalDateTime.now(); // Default to now, DB might override
        this.isDraft = false;
        this.title = "";
        this.mood = "";
    }

    // Constructor for creating drafts
    public JournalEntry(String content, boolean isDraft) {
        this.content = content;
        this.timestamp = LocalDateTime.now();
        this.isDraft = isDraft;
        this.title = "";
        this.mood = "";
    }

    // Constructor for creating entries with all fields
    public JournalEntry(String content, boolean isDraft, String title, String mood) {
        this.content = content;
        this.timestamp = LocalDateTime.now();
        this.isDraft = isDraft;
        this.title = title;
        this.mood = mood;
    }

    // Constructor for loading entries from the database
    public JournalEntry(int id, String content, LocalDateTime timestamp) {
        this.id = id;
        this.content = content;
        this.timestamp = timestamp;
        this.isDraft = false;
        this.title = "";
        this.mood = "";
    }

    // Full constructor for loading entries from database
    public JournalEntry(int id, String content, LocalDateTime timestamp, boolean isDraft, String title, String mood) {
        this.id = id;
        this.content = content;
        this.timestamp = timestamp;
        this.isDraft = isDraft;
        this.title = title;
        this.mood = mood;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getContent() {
        return content;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public boolean isDraft() {
        return isDraft;
    }
    public LocalDateTime getCreatedAt() {
        return timestamp; // Simply return the timestamp
    }

    public String getTitle() {
        return title;
    }

    public String getMood() {
        return mood;
    }

    // Setters
    public void setId(int id) {
        this.id = id;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public void setDraft(boolean draft) {
        isDraft = draft;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

    @Override
    public String toString() {
        // Keep it concise for potential list views, maybe just show date/time and start of content
        String shortContent = content.length() > 50 ? content.substring(0, 50) + "..." : content;
        String draftStatus = isDraft ? " (DRAFT)" : "";
        return "JournalEntry{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", content='" + shortContent + '\'' + // Avoid printing very long content
                ", mood='" + mood + '\'' +
                ", timestamp=" + timestamp +
                draftStatus +
                '}';
    }
}