package mindgarden.model;

import java.time.LocalDateTime;

/**
 * Represents a single mood entry recorded by the user.
 */
public class MoodEntry {

    private int id; // Database primary key
    private String moodType; // e.g., "Happy", "Sad", "Anxious"
    private LocalDateTime timestamp;

    // Constructor for creating new entries (ID is auto-generated by DB)
    public MoodEntry(String moodType) {
        this.moodType = moodType;
        this.timestamp = LocalDateTime.now(); // Default to now, DB might override
    }

    // Constructor for loading entries from the database
    public MoodEntry(int id, String moodType, LocalDateTime timestamp) {
        this.id = id;
        this.moodType = moodType;
        this.timestamp = timestamp;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getMoodType() {
        return moodType;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    // Setters (optional, depending on usage)
    public void setId(int id) {
        this.id = id;
    }

    public void setMoodType(String moodType) {
        this.moodType = moodType;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        return "MoodEntry{" +
               "id=" + id +
               ", moodType='" + moodType + '\'' +
               ", timestamp=" + timestamp +
               '}';
    }
}
